### ISSUE TITLE
Display errors in popup dialog

### ISSUE THREAD

**Issue by cmars** [pjmlp/gwc-rs#1]
A file error during processing will give an incomplete & possibly incorrect count without indicating there was a problem. It'd be nice if `std:io:error` were surfaced to the user in a popup dialog (looking at `count_words`).

**Comment by pjmlp** [comment]
Thanks for the suggestion, I will have a look at it.

**Comment by pjmlp** [comment]
I have implemented your suggestion, although the message display could have been made prettier. :)

Hope it is ok to mention you on the readme.
